/**
 * Build the demo's two generated files.
 *
 * `examples.js` is generated rather than written so the page cannot drift from
 * the corpus the tests measure: the examples ARE fixtures/llmdocs.json, and the
 * prompt the model is given IS docs/AUTHORING.md — the same catalog the
 * converter enforces.
 */

import {execFileSync} from 'node:child_process';
import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(resolve(root, p), 'utf8');

const PICKS = [
  ['sonnet-T1', 'A question with three choices'],
  ['gpt-T2', 'A dangerous approval'],
  ['sonnet-T4', 'A form: text fields and choices'],
  ['gpt-T3', 'A table of diffs, then a question'],
];

const docs = JSON.parse(read('fixtures/llmdocs.json'));
const missing = PICKS.filter(([id]) => !docs[id]).map(([id]) => id);
if (missing.length) {
  throw new Error(`fixtures/llmdocs.json has no ${missing.join(', ')}`);
}

const prompt = `${read('docs/AUTHORING.md')}
Answer in MDX using only those components. Keep it short: a few lines of prose,
then one <Ask>. Output the document only — no code fences, no commentary.`;

writeFileSync(
  resolve(root, 'demo/examples.js'),
  `// Generated by scripts/build-demo.mjs — edit the fixtures, not this file.

export const EXAMPLES = [
${PICKS.map(
  ([id, label]) => `  {
    id: ${JSON.stringify(id)},
    label: ${JSON.stringify(label)},
    source: ${JSON.stringify(docs[id])},
  },`,
).join('\n')}
];

export const AUTHORING_PROMPT = ${JSON.stringify(prompt)};
`,
);

// The library is bundled; its dependencies are left external so the page's
// import map resolves them from the CDN, like everything else on it.
execFileSync(
  'npx',
  [
    'esbuild',
    'src/index.ts',
    '--bundle',
    '--format=esm',
    '--external:unified',
    '--external:remark-parse',
    '--external:remark-gfm',
    '--external:remark-mdx',
    '--outfile=demo/mdx-a2ui.js',
  ],
  {cwd: root, stdio: 'inherit'},
);
